name: yun_music
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  get: ^4.6.6
  get_storage: ^2.1.1
  #刷新控件
  pull_to_refresh: ^2.0.0
  flutter_easyloading: ^3.0.5
  android_intent_plus: ^5.0.2
  json_annotation: ^4.9.0
  dio: ^5.5.0+1
  connectivity_plus: ^6.0.1
  dio_http2_adapter: ^2.4.0
  logger: ^2.4.0
  event_bus: ^2.0.0
  fluttertoast: ^8.2.6
  keframe: ^3.0.0
  card_swiper: ^3.0.1
  cached_network_image: ^3.3.1
  palette_generator: ^0.3.3+4
  intl: ^0.19.0
  just_audio: ^0.9.39
  modal_bottom_sheet: ^3.0.0
  image_pixels: ^3.0.2

dev_dependencies:

  json_serializable: ^6.8.0
  # flutter pub run build_runner build
  build_runner: ^2.4.11


  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/anim/
    - assets/anim/loading/
    - assets/json/


